package com.ortin.gesturetranslator.presentation.ui.theme

import androidx.compose.ui.graphics.Color

// Light color scheme

val md_theme_light_primary = Color(0xFF99405D)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFD9E1)
val md_theme_light_onPrimaryContainer = Color(0xFF3F001B)
val md_theme_light_secondary = Color(0xFF74565E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFD9E1)
val md_theme_light_onSecondaryContainer = Color(0xFF2B151B)
val md_theme_light_tertiary = Color(0xFF7B5734)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDCBF)
val md_theme_light_onTertiaryContainer = Color(0xFF2D1600)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_outline = Color(0xFF847376)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF201A1B)
val md_theme_light_surface = Color(0xFFFFF8F8)
val md_theme_light_onSurface = Color(0xFF201A1B)
val md_theme_light_surfaceVariant = Color(0xFFF3DDE1)
val md_theme_light_onSurfaceVariant = Color(0xFF514346)
val md_theme_light_inverseSurface = Color(0xFF352F30)
val md_theme_light_inverseOnSurface = Color(0xFFFAEEEF)
val md_theme_light_inversePrimary = Color(0xFFFFB1C5)
val md_theme_light_surfaceTint = Color(0xFF99405D)
val md_theme_light_outlineVariant = Color(0xFFD6C2C5)
val md_theme_light_scrim = Color(0xFF000000)

// Dark color cheme

val md_theme_dark_primary = Color(0xFFFFB1C5)
val md_theme_dark_onPrimary = Color(0xFF5E112F)
val md_theme_dark_primaryContainer = Color(0xFF7B2946)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD9E1)
val md_theme_dark_secondary = Color(0xFFE3BDC5)
val md_theme_dark_onSecondary = Color(0xFF422930)
val md_theme_dark_secondaryContainer = Color(0xFF5B3F46)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFD9E1)
val md_theme_dark_tertiary = Color(0xFFEEBD92)
val md_theme_dark_onTertiary = Color(0xFF472A0A)
val md_theme_dark_tertiaryContainer = Color(0xFF61401F)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDCBF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_outline = Color(0xFF9E8C90)
val md_theme_dark_background = Color(0xFF201A1B)
val md_theme_dark_onBackground = Color(0xFFECE0E1)
val md_theme_dark_surface = Color(0xFF171213)
val md_theme_dark_onSurface = Color(0xFFCFC4C5)
val md_theme_dark_surfaceVariant = Color(0xFF514346)
val md_theme_dark_onSurfaceVariant = Color(0xFFD6C2C5)
val md_theme_dark_inverseSurface = Color(0xFFECE0E1)
val md_theme_dark_inverseOnSurface = Color(0xFF201A1B)
val md_theme_dark_inversePrimary = Color(0xFF99405D)
val md_theme_dark_surfaceTint = Color(0xFFFFB1C5)
val md_theme_dark_outlineVariant = Color(0xFF514346)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF783C4E)
